---
- name: create default directories
  file: path={{SGE_ROOT}}/default/common/ state=directory
  when: ansible_os_family == "RedHat"

- name: Set the SGE qmaster node
  action: copy dest={{SGE_ROOT}}/default/common/act_qmaster content={{sge_server_name}}
  notify: restart {{EXEC_SERVICE}}
